### ISSUE TITLE
Cannot install on windows 10

### ISSUE THREAD

**Issue by dansha** [bogus34/bookshelf-signals#1]
when I 
npm i -S bookshelf-signals

I get
 ..\src\unix_dgram.cc(9): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory [C:\User
s\shami\dev\sergata\b2b\node_modules\unix-dgram\build\unix_dgram.vcxproj]

**Comment by bogus34** [comment]
Seems to be not related with bookshelf-signals directly. This module doesn't contains any C code.
