### ISSUE TITLE
EventsHub.__super__ is undefined

### ISSUE THREAD

**Issue by dantman** [bogus34/bookshelf-signals#2]
I get this error while attempting to use this plugin.

![screenshot_20161210-035439](https://cloud.githubusercontent.com/assets/53399/21073167/aae39828-be8c-11e6-845e-a2115174e538.png)

The issue simply seems to be that `bookshelf/lib/base/events` is actually an ES6 style export. Meaning `.default` should be added after the require.

**Comment by bogus34** [comment]
Yes, looks like this lib should be updated for newer versions of Bookshelf. Thanks for reporting!

**Comment by bogus34** [comment]
fixed in v0.1.2
